### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by codingleo** [KnisterPeter/jreact#6]
Hello!

I'm thinking about to create a react app with server-side rendering in JAVA. I already listened about **nashorn** and **JReact**. I think it should have more examples for more complex apps.

I have some doubts:
- If I read a .jsx file, is it will get the required files recursively as webpack / browserify?

**Comment by KnisterPeter** [comment]
Good point. I will provide some more examples in the next time.

**Comment by codingleo** [comment]
Thanks @KnisterPeter! I'll take a look at the code and try to help with more examples too!

**Comment by KnisterPeter** [comment]
Have a look at this: https://github.com/KnisterPeter/jreact-examples
