### ISSUE TITLE
Is this more scalable than NodeJS Cluster?

### ISSUE THREAD

**Issue by idibidiart** [KnisterPeter/jreact#8]
Hi

Awesome that you've made this.

I'm wondering, is it more scalable (cpu load wise) than running REACT SSR on NodeJS in cluster mode?

Can you provide the rationale for choosing Java for SSR?

**Comment by KnisterPeter** [comment]
Ich would not recommend to use it if you can usw node.js. JS in the JVM is far slower and resource intensive compared to node.js.
But there are environments where node.js is not available.

**Comment by idibidiart** [comment]
oh i see ty
